package com.scp.web.common;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import java.util.List;

public interface IWebUICommon {
    public void capturePageScreenshot();
    public void capturePageScreenshot(String fileName);
    public void clearText(String xpath);
    public void clearText(By location);
    public void clearText(WebElement element);
    public void clickElement(String xpath);
    public void clickElement(By location);
    public void clickElement(WebElement element);
    public void clickAndHoldElement(String xpath);
    public void clickAndHoldElement(By location);
    public void clickAndHoldElement(WebElement element);
    public void clickText(String text);
    public void dragAndDrop(String sourceXpath, String destinationXpath);
    public void dragAndDrop(By sourceLocation, By destinationLocation);
    public void dragAndDrop(WebElement sourceElement, WebElement destinationElement);
    public void doubleClickElement(String xpath);
    public void doubleClickElement(By location);
    public void doubleClickElement(WebElement element);
    public void elementAttributeShouldMatch(String xpath, String attribute, String expect);
    public void elementAttributeShouldMatch(By location, String attribute, String expect);
    public void elementAttributeShouldMatch(WebElement element, String attribute, String expect);
    public void elementAttributeShouldNotMatch(String xpath, String attribute, String expect);
    public void elementAttributeShouldNotMatch(By location, String attribute, String expect);
    public void elementAttributeShouldNotMatch(WebElement element, String attribute, String expect);
    public void elementShouldBeDisabled(String xpath);
    public void elementShouldBeDisabled(By location);
    public void elementShouldBeDisabled(WebElement element);
    public void elementShouldBeEnabled(String xpath);
    public void elementShouldBeEnabled(By location);
    public void elementShouldBeEnabled(WebElement element);
    public void elementShouldBeVisible(String xpath);
    public void elementShouldBeVisible(By location);
    public void elementShouldBeVisible(WebElement element);
    public void elementShouldContainText(String xpath, String text);
    public void elementShouldContainText(By location, String text);
    public void elementShouldContainText(WebElement element, String text);
    public void elementShouldNotContainText(String xpath, String text);
    public void elementShouldNotContainText(By location, String text);
    public void elementShouldNotContainText(WebElement element, String text);
    public void elementTextShouldBe(String xpath, String text);
    public void elementTextShouldBe(By location, String text);
    public void elementTextShouldBe(WebElement element, String text);
    public void elementValueShouldBe(String xpath, String value);
    public void elementValueShouldBe(By location, String value);
    public void elementValueShouldBe(WebElement element, String value);
    public void elementTextShouldNotBe(String xpath, String text);
    public void elementTextShouldNotBe(By location, String text);
    public void elementTextShouldNotBe(WebElement element, String text);
    public void elementValueShouldNotBe(String xpath, String value);
    public void elementValueShouldNotBe(By location, String value);
    public void elementValueShouldNotBe(WebElement element, String value);
    public String getCurrentUrl();
    public WebElement getElement(String xpath);
    public WebElement getElement(By location);
    public List<WebElement> getElements(String xpath);
    public List<WebElement> getElements(By location);
    public WebElement getElement(String xpath, long timeout);
    public WebElement getElement(By location, long timeout);
    public List<WebElement> getElements(String xpath, long timeout);
    public List<WebElement> getElements(By location, long timeout);
    public String getElementAttribute(String xpath, String attribute);
    public String getElementAttribute(By location, String attribute);
    public String getElementAttribute(WebElement element, String attribute);
    public int getNumberOfListElement(String xpath);
    public int getNumberOfListElement(By location);
    public int getNumberOfListElement(List<WebElement> elementList);
    public String getSourcePage();
    public String getText(String xpath);
    public String getText(By location);
    public String getText(WebElement element);
    public void hoverElement(String xpath);
    public void hoverElement(By location);
    public void hoverElement(WebElement element);
    public void inputText(String xpath, String text);
    public void inputText(By location, String text);
    public void inputText(WebElement element, String text);
    public void navigateToURL(String url);
    public void pageShouldContainText(String text);
    public void pageShouldNotContainText(String text);
    public void pageShouldContainElement(String xpath);
    public void pageShouldContainElement(By location);
    public void pageShouldNotContainElement(String xpath);
    public void pageShouldNotContainElement(By location);
    public void reloadCurrentPage();
    public void waitUntilPageContainText(String text);
    public void waitUntilPageContainText(String text, long millis);
    public void waitUntilPageContainElement(String xpath);
    public void waitUntilPageContainElement(By location);
    public void waitUntilPageNotContainElement(String xpath);
    public void waitUntilPageNotContainElement(By location);
    public void waitUntilPageContainElement(String xpath, long millis);
    public void waitUntilPageContainElement(By location, long millis);
    public void waitUntilPageNotContainElement(String xpath, long millis);
    public void waitUntilPageNotContainElement(By location, long millis);
}
